application: visualizing-music
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /
  static_files: index.html
  upload: index.html

- url: /(.*)
  static_files: \1
  upload: /(.*)

# - url: /.*
#   script: main.app

# libraries:
# - name: webapp2
#   version: "2.5.2"
# - name: jinja2
#   version: latest
