name: Deploy to Google App Engine
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '.git**'
      - '**.md'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          credentials: ${{ secrets.GCLOUD_AUTH }}
