name: Deploy to Google Cloud Platform
on: push
jobs:
  GCPDeploy:
    name: GCP Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: GCP Authenticate
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
    - name: GCP Set Project
      uses: actions/gcloud/cli@master
      with:
        args: config set project ${{ secrets.GCLOUD_PROJECT_ID }}
    - name: GCP App Deploy
      uses: actions/gcloud/cli@master
      with:
        args: app deploy app.yaml
