name: Deploy to Google Cloud Platform
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '.git**'
      - '**.md'
jobs:
  GCPDeploy:
    name: GCP Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
      - run: gcloud app deploy
